### ISSUE TITLE
Fail to build with "--disable-cplugins" after commit 15a6d00

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#6028]
### mpv version and platform
mpv 45beb70
MacOS 10.13.6 (17G65)

### Reproduction steps
`./bootstrap.py && ./waf configure --disable-cplugins && ./waf build`

### Actual behavior
`AttributeError: 'task_gen' object has no attribute 'link_task'`
### Log file
[https://0x0.st/sV7y.txt](https://0x0.st/sV7y.txt)

**Comment by Akemi** [comment]
should be fixed with #6029.

**Comment by macdavis** [comment]
Confirmed, thanks!
