### PR TITLE
swift build fixes

### PR DESCRIPTION
**Pull request by Akemi**

### CODE REVIEW

**Comment by Hamuko** [comment]
Have you tested building with `--enable-libmpv-shared`? I tried updating mpv through Homebrew yesterday and ran into issues when Homebrew tried to compile mpv.

```
[416/419] Linking build/libmpv.dylib
[417/419] Linking build/mpv
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC11macOS_swift7CocoaCB", referenced from:
      objc-class-ref in macosx_application.m.26.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/private/tmp/mpv-20180213-10122-1pg8azd/build'
Build failed
```

I then grabbed the git master onto my machine and compiled it with no options. Worked fine. Got a build, watched some videos with it fine (as long as I used `--vo=opengl-cb`).

Then I tried tacking on some options to the configuration phase from the Homebrew formula. Running `python3 waf distclean && python3 waf configure --enable-libmpv-shared && python3 waf` resulted in the same issue as when Homebrew tried to build mpv. As far as I could tell, c82fed85b985d30806b1982c1f58f50a4edbc3fa is the first commit that resulted in the same error.

```
[415/417] Linking build/mpv
[416/417] Linking build/libmpv.dylib
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC11macOS_swift7CocoaCB", referenced from:
      objc-class-ref in macosx_application.m.26.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

git bisect fingered 235eb60671c899d55b1174043940763b250fa3b8 as the absolute first bad commit when I ran `git bisect run sh -c "python3 waf distclean && python3 waf configure --enable-libmpv-shared && python3 waf"`, but there the build fails when it can't find ffmpeg.

Tested on a Hackintosh with 10.13.2 and on a late 2016 MacBook Pro with 10.13.3. Both hated using `--enable-libmpv-shared` but compiled without it.

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/pull/4833#issuecomment-364999323
https://github.com/mpv-player/mpv/pull/4833#issuecomment-365097646
yeah i am aware of those issues.

**Comment by Akemi** [comment]
i will try to fix them shortly. probably after dinner since i just came home.

i wasn't yet able to reproduce the ffmpeg linking issue, but @AirPort fixed them by disabling `libsoxr` and `libtheora` in ffmpeg.

**Comment by Akemi** [comment]
i fixed the linking error with libmpv with the second commit on #5517. would be nice if you could confirm this issue fixed. also it would be nice if any other issue persist that a new issue is opened, otherwise i might lose the overview of the various issues i caused with this.

**Comment by Hamuko** [comment]
Yeah, builds just fine now. Enabled all of the options that the Homebrew formula enables and got a working build out of it.

**Comment by Akemi** [comment]
great.
