### ISSUE TITLE
lua.c doesn't build

### ISSUE THREAD

**Issue by tewe** [mpv-player/mpv#1197]
```
../player/lua.c:1259:9: error: implicit declaration of function 'kill' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        kill(pid, SIGKILL);
```

Probably introduced in https://github.com/mpv-player/mpv/commit/987146362e35820cd96d7de4f48b13ec4ee25d7c
