### ISSUE TITLE
regression: compile failure with old libbluray

### ISSUE THREAD

**Issue by kevmitch** [mpv-player/mpv#672]
With mpv-build on Ubuntu 12.04 where  libbluray-dev=1:0.2.1+git20111208.63e308d-3

```
$ scripts/mpv-config && scripts/mpv-build 
...
[130/239] c: stream/stream_dvb.c -> build/stream/stream_dvb.c.11.o
../stream/stream_bluray.c: In function ‘handle_event’:
../stream/stream_bluray.c:135:10: error: ‘BD_EVENT_IDLE’ undeclared (first use in this function)
../stream/stream_bluray.c:135:10: note: each undeclared identifier is reported only once for each function it appears in
```

[full output of scripts/mpv-config](http://pastebin.com/kpCHCaTz)
[full output of scripts/mpv-build](http://pastebin.com/YK1YnR9h)
