### ISSUE TITLE
../video/out/vo_drm.c:25:10: fatal error: 'linux/vt.h' file not found

### ISSUE THREAD

**Issue by jbeich** [mpv-player/mpv#1834]
Where VT_SETMODE et al. are defined differs by the system: [Solaris](http://src.illumos.org/source/search?defs=VT_SETMODE&project=illumos-gate), [BSDs](http://bxr.su/search?defs=VT_SETMODE). Regressed by f3c8c61.

```
$ ./waf build
Waf: Entering directory `.../mpv/build'
[201/225] Compiling video/out/vo_drm.c
../video/out/vo_drm.c:25:10: fatal error: 'linux/vt.h' file not found
#include <linux/vt.h>
         ^
1 error generated.
```

**Comment by rr-** [comment]
@jbeich do you suppose there's any portable way for it to include them without littering with `#ifdef` and hardcoding manually with `#define`?

**Comment by rr-** [comment]
Compile errors should be gone with bd5d047c893cda0b533f9457a6fb2bfbd60de13e at expense of losing support for DRM on BSD (which would be half-baked anyway.)

**Comment by rr-** [comment]
@jbeich did it work for you?

**Comment by jbeich** [comment]
Yes, it builds fine now with
```
Checking for DRM : vt.h not found
```
