### ISSUE TITLE
Howto solve or bypass : "tls: A TLS fatal alert has been received."

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#4776]
### mpv version and platform

`mpv 0.25.0-7bfeb8b-amended on Ubuntu 14.04.5 LTS`

### Reproduction steps
mpv http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
### Expected behavior
Playing the video
### Actual behavior
```
[ffmpeg] tls: A TLS fatal alert has been received.
[stream] Failed to open http://spankbang.com/_94kg/IjE1MDI5ODk3NDQuMyI.p0Et41IkRxNpN0zPvKAt3HjKBOQ/title/720p__mp4.
[cplayer] Opening failed or was aborted: http://spankbang.com/_94kg/IjE1MDI5ODk3NDQuMyI.p0Et41IkRxNpN0zPvKAt3HjKBOQ/title/720p__mp4
```
### Log file

```
$ $(which mpv) --no-config -v http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
[cplayer] Command line options: '--no-config' '-v' 'http://spankbang.com/94kg/video/were+did+you+find+her+vol+11'
[cplayer] mpv 0.25.0-7bfeb8b-amended (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Jun 27 03:36:23 UTC 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.66.100
[cplayer]    libavcodec      57.99.102
[cplayer]    libavformat     57.75.100
[cplayer]    libswscale      4.7.101
[cplayer]    libavfilter     6.94.100
[cplayer]    libswresample   2.8.100
[cplayer] ffmpeg version: git-2017-06-25-73ea2a0
[cplayer] 
[cplayer] Configuration: ./waf configure --enable-pdf-build --enable-dvbin --enable-dvdread --enable-dvdnav --prefix=/usr --confdir=/etc/mpv
[cplayer] List of enabled features: 52deb alsa asm atomics audio-input avutil-content-light-level avutil-imgcpy-uc build-date cplayer cplugins cuda-hwaccel debug-build dlopen drm dvbin dvdnav dvdread dvdread-common encoding fchmod gl gl-x11 glibc-thread-name glob gnuc iconv is_ffmpeg jack jpeg lcms2 libass libass-osd libav libavcodec libavdevice libbluray libdl libm librt libv4l2 linux-fstatfs lua nanosleep optimize oss-audio posix posix-or-mingw posix-spawn pthreads pulse rubberband shm subprocess termios tv tv-v4l2 uchardet vaapi vaapi-glx vaapi-hwaccel vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h x11 xv zlib
[global] config path: '' -> '-'
[cplayer] Setting option 'config' = 'no' (flags = 8)
[cplayer] Setting option 'v' = '' (flags = 8)
[osc] Loading lua script @osc.lua...
[osc] loading mp.defaults
[osc] loading @osc.lua
[osc] lua-settings/osc.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[cplayer] mouse_leave script-binding osc/__keybinding2
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[cplayer] mouse_btn2 script-binding osc/__keybinding5
[cplayer] mouse_btn3 script-binding osc/__keybinding6
[cplayer] mouse_btn4 script-binding osc/__keybinding7
[cplayer] axis_up script-binding osc/__keybinding8
[cplayer] axis_down script-binding osc/__keybinding9
[cplayer] mouse_btn0_dbl ignore
[cplayer] shift+mouse_btn0_dbl ignore
[cplayer] mouse_btn2_dbl ignore
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[input, ]
[cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding10
[cplayer] , default]
[cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading lua script @ytdl_hook.lua...
[ytdl_hook] loading mp.defaults
[cplayer] Run command: disable-section, flags=0, args=[input]
[osd/libass] Shaper: FriBidi 0.19.6 (SIMPLE) HarfBuzz-ng 1.0.1 (COMPLEX)
[osd/libass] Setting up fonts...
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] config path: 'watch_later' -> '-'
[global] config path: 'watch_later' -> '-'
[cplayer] Playing: http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
[cplayer] Running hook: ytdl_hook/on_load
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[ytdl_hook] youtube-dl succeeded! 
[cplayer] Set property: file-local-options/user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)" -> 1
[cplayer] Set property: file-local-options/http-header-fields=["Cookie: country=FR; __cfduid=d2fab5e1e4f8e23d2944b07c1d9a85e761502989842"] -> 1
[cplayer] Set property: stream-open-filename="http://spankbang.com/_94kg/IjE1MDI5ODk3NDQuMyI.p0Et41IkRxNpN0zPvKAt3HjKBOQ/title/720p__mp4" -> 1
[cplayer] Set property: file-local-options/force-media-title="WERE DID YOU FIND HER? VOL #11" -> 1
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[ffmpeg] Opening http://spankbang.com/_94kg/IjE1MDI5ODk3NDQuMyI.p0Et41IkRxNpN0zPvKAt3HjKBOQ/title/720p__mp4
[ffmpeg] tls: A TLS fatal alert has been received.
[stream] Failed to open http://spankbang.com/_94kg/IjE1MDI5ODk3NDQuMyI.p0Et41IkRxNpN0zPvKAt3HjKBOQ/title/720p__mp4.
[cplayer] Opening failed or was aborted: http://spankbang.com/_94kg/IjE1MDI5ODk3NDQuMyI.p0Et41IkRxNpN0zPvKAt3HjKBOQ/title/720p__mp4
[cplayer] finished playback, loading failed (reason 4)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Errors when loading file)
[ytdl_hook] Exiting...
[osc] Exiting...
$ echo $?
2
```
### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wiiaboo** [comment]
Try just running `youtube-dl` on the same URL on its own. If it's also broken it might be a youtube-dl issue.

**Comment by sebma** [comment]
No pb. with `youtube-dl` : 
```
$ youtube-dl --ignore-config --get-url http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
http://spankbang.com/_94kg/IjE1MDI5ODk3NDQuMyI.p0Et41IkRxNpN0zPvKAt3HjKBOQ/title/720p__mp4
```

**Comment by wiiaboo** [comment]
Don't just --get-url. Download the video.

**Comment by sebma** [comment]
No pb : 

```
$ youtube-dl --ignore-config --prefer-ffmpeg http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
[SpankBang] 94kg: Downloading webpage
[SpankBang] 94kg: Checking 1080p video format URL
[SpankBang] 94kg: 1080p video format URL is invalid, skipping
[SpankBang] 94kg: Checking 720p video format URL
[SpankBang] 94kg: Checking 480p video format URL
[SpankBang] 94kg: Checking 240p video format URL
[download] Destination: WERE DID YOU FIND HER VOL #11-94kg.mp4
[download] 100% of 92.99MiB in 04:48
```

**Comment by wiiaboo** [comment]
Works for me on Windows with Secure Channel and also with LibreSSL (OpenSSL).
Could you try it with ffmpeg? Use the URL from youtube-dl's --get-url.

**Comment by mc4man** [comment]
I guess you're using some form of ubuntu 14.04. That package needs updating to work with latest/recent youtube-dl. Try in a few hrs...
If on 16.04 your url works fine on latest package.

**Comment by mc4man** [comment]
So while the package needed updating for recent youtube-dl in this case something else.
With ffmpeg-3.3.2 doesn't work - 
[tls @ 0x24ccf00] A TLS fatal alert has been received.
http://spankbang.com/_94kg/IjE1MDI5ODk3NDQuMyI.p0Et41IkRxNpN0zPvKAt3HjKBOQ/title/720p__mp4: Input/output error
(both ffmpeg & mpv's build are using gnutls

**Comment by wiiaboo** [comment]
So it's a ffmpeg bug, cool.

**Comment by mc4man** [comment]
Not really an ffmpeg bug, nor mpv. Seems python related, in 14.04 it's 2.7.5
maybe here is the deal
https://github.com/rg3/youtube-dl/issues/9666

**Comment by wiiaboo** [comment]
Shouldn't be python-related. There's nothing python in mpv.

**Comment by mc4man** [comment]
Well youtube-dl is & whatever the methods of gnutls or ssl in ffmpeg I don't know. (but there is something python related..
For example - 
The op's errors aren't what you'd expect in a default 14.04.5 & python 2.7.6, you'd see this instead,
$ python -V
Python 2.7.6

`$ youtube-dl --ignore-config --prefer-ffmpeg http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
[SpankBang] 94kg: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))`
and 
`$ mpv --no-config http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
Playing: http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] tls: A TLS fatal alert has been received.
Failed to open http://spankbang.com/94kg/video/were+did+you+find+her+vol+11`

Now exporting PATH to python-2.7.9 I put in /opt
$ export PATH="/opt/python-current/bin:$PATH"
$ python -V
Python 2.7.9
the mpv error now changes,
`~$ mpv --no-config http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
Playing: http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
[ffmpeg] tls: A TLS fatal alert has been received.
Failed to open http://spankbang.com/_94kg/IjE1MDMwMTU5ODIuMjQi.wL3olHEXKPkFDxJa0eot9uRhGdE/title/720p__mp4.`
And youtube-dl works
`$ youtube-dl --ignore-config --prefer-ffmpeg http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
[SpankBang] 94kg: Downloading webpage
[SpankBang] 94kg: Checking 1080p video format URL
[SpankBang] 94kg: 1080p video format URL is invalid, skipping
[SpankBang] 94kg: Checking 720p video format URL
[SpankBang] 94kg: Checking 480p video format URL
[SpankBang] 94kg: Checking 240p video format URL
[download] Destination: WERE DID YOU FIND HER VOL #11-94kg.mp4
[download]   8.6% of 92.99MiB at  5.48MiB/s ETA 00:15^C
ERROR: Interrupted by user`

So I suspect the op has put a newer python in his $PATH, maybe if he builds the whole deal himself it'll work, maybe not..

**Comment by mc4man** [comment]
As comparison, in system where mpv build is exactly the same but  the default python is past 2.7.9 it all works fine
Ex.
$ python -V
Python 2.7.12
`$ mpv --no-config https://spankbang.com/1g3xa/video/courtney+taylor+hot+nuru+massage+creampie
Playing: https://spankbang.com/1g3xa/video/courtney+taylor+hot+nuru+massage+creampie
 (+) Video --vid=1 (*) (h264 1280x720 30.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 1ch 24000Hz)
AO: [pulse] 24000Hz mono 1ch float
VO: [opengl] 1280x720 yuv420p
AV: 00:00:03 / 00:23:29 (0%) A-V:  0.000 Cache:  8s+8KB
`

**Comment by wiiaboo** [comment]
But there is no error on extracting youtube-dl or even downloading using it, so it's absolutely nothing to do with python. At most something directly to do with GnuTLS or FFmpeg release missing some backported patch.

**Comment by mc4man** [comment]
"But there is no error on extracting youtube-dl or even downloading using it, so it's absolutely nothing to do with python."
What??
Does this not look like an 'error'? (3 comments ^

$ python -V
Python 2.7.6

`$ youtube-dl --ignore-config --prefer-ffmpeg http://spankbang.com/94kg/video/were+did+you+find+her+vol+11 [SpankBang] 94kg: Downloading webpage ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))`

Overall doesn't matter, it's up to the op to either rebuild involved sources to use python-2.7.9 or higher, (may work) or just upgrade to some distro where the default system python is 2.7.9 or newer

**Comment by wiiaboo** [comment]
That **is** a python error. The OP is **not** a python error.

**Comment by mc4man** [comment]
To the OP, if you return.
To make that url work in your chosen (14.04.x) you need to do 2 things
1. the embedded ffmpeg needs to use/be built off of  openssl (--enable-openssl) vs gnutls (--enable-gnutls)
2. You need to use python-2.7.9 or greater (for youtube-dl

It's quite likely you've already satisfied the later. Maybe I'll switch the ppa build to libssl-dev vs. libgnutls-dev, not sure.. (don't quite remember why I choose libgnutls-dev in 1st. place.

Ex. at risk of being redundant (though notice mpv direct produces new simple error with openssl),  same everything rebuilt here using libssl-dev dep

$ mpv --no-config http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
Playing: http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
Failed to recognize file format.

`$ export PATH="/opt/python-current/bin:$PATH"`

$ mpv --no-config http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
Playing: http://spankbang.com/94kg/video/were+did+you+find+her+vol+11
 (+) Video --vid=1 (*) (h264 720x404 24.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 1ch 24000Hz)

File tags:
 Title: 1fuckdatecom Pov wars black girls gets fucke | Redtube Free HD Porn Videos, Amateur Movies & Clips
AO: [pulse] 24000Hz mono 1ch float
VO: [opengl] 720x404 => 720x405 yuv420p
AV: 00:00:00 / 00:13:38 (0%) A-V:  0.000 Cache:  9s+4MB

**Comment by sebma** [comment]
I re-installed `youtube-dl` with python3 : `sudo -H pip3 install -U youtube-dl` and updated mpv release to 0.26 : 
```
$ apt-cache policy mpv
mpv:
  Installed: 2:0.26.0+git1~trusty1
  Candidate: 2:0.26.0+git1~trusty1
  Version table:
 *** 2:0.26.0+git1~trusty1 0
        500 http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     2:0.15.0+git7~trusty 0
        500 http://fr.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```
and it fixed the problem but I don't know why

**Comment by mc4man** [comment]
'Fixed' because,
1. The build you're using has switched to openssl as gnutls in 14.04 was deficient for these type urls 
    That solved mpv/ffpeg/tls problem
2. You're using by some means python-2.7.9 or higher. That solves the problem in youtube-dl

**Comment by sebma** [comment]
@mc4man Thanks for your explanation :)
