### ISSUE TITLE
build failed when configure --disable-gl

### ISSUE THREAD

**Issue by zhangn1985** [mpv-player/mpv#4137]
```
[166/202] Compiling player/loadfile.c
In file included from /media/storage/player/mpv/video/out/opengl/hwdec.h:4:0,
                 from ../options/options.c:43:
/media/storage/player/mpv/video/out/opengl/common.h:45:19: fatal error: GL/gl.h: 没有那个文件或目录
 #include <GL/gl.h>
                   ^
compilation terminated.

Waf: Leaving directory `/media/storage/player/mpv/build'
Build failed
 -> task in 'objects' failed (exit status 1): 
	{task 3057465936L: c options.c -> options.c.14.o}
['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-pthread', '-I/media/storage/player/mpv/build', '-I/media/storage/player/mpv', '-I/usr/local/include', '-I/usr/include/lua5.2', '-I/usr/include/alsa', '-I/usr/include/harfbuzz', '-I/usr/include/freetype2', '-I/usr/include/fribidi', '-DHAVE_GBM=1', '-DHAVE_LIBAVCODEC=1', '-DHAVE_52DEB=1', '-DHAVE_LIBAV=1', '-DHAVE_ALSA=1', '-DHAVE_LIBAVDEVICE=1', '-DPATH_DEV_DSP="/dev/dsp"', '-DPATH_DEV_MIXER="/dev/mixer"', '-DHAVE_VDPAU=1', '-DHAVE_X11=1', '-DHAVE_LIBASS=1', '../options/options.c', '-c', '-o', '/media/storage/player/mpv/build/options/options.c.14.o']

```

after dig, I found this issue introduced by 9d68d8fb0f806f25408435c09ac5dbbe34b95462

**Comment by wiiaboo** [comment]
Fixed in https://github.com/mpv-player/mpv/commit/212f6c8206bd4dcc7d8970c5f1632823ae4e783a.
