### ISSUE TITLE
Build failure with --enable-dvdnav

### ISSUE THREAD

**Issue by Slider-Whistle** [mpv-player/mpv#6282]
### mpv version and platform
0.29.1; Using modified community slackbuild on Slackware 14.2
### Reproduction steps
BUILD_OPTS="--enable-dvdnav" ./mpv.SlackBuild
### Expected behavior
Successful build
### Actual behavior
Build fails when compiling files related to libdvdnav
### Log file
https://pastebin.com/raw/86mEcfKW

Compilation seems to fail with a similar error with any file related to dvdnav. To spare you the effort of scrolling down to the bottom of the log where the error actually happens, I'll paste it here:

[ 86/228] Compiling stream/stream_dvdnav.c
[ 87/228] Compiling video/out/gpu/shader_cache.c
In file included from ../stream/stream_dvdnav.c:34:0:
/usr/include/dvdnav/dvdnav.h:58:9: error: unknown type name ‘dvd_reader_stream_cb’
 typedef dvd_reader_stream_cb dvdnav_stream_cb;
         ^

**Comment by Slider-Whistle** [comment]
For the record, this same error occurs when trying to compile the version the slackbuild is natively configured to use.

**Comment by jeeb** [comment]
What is the version of dvdnav you have? I see we test for `dvdnav >= 4.2.0` and latest upstream is seemingly `6.0.0`, which seems to have some symbol hiding that would hide `dvdread_*` symbols (https://code.videolan.org/videolan/libdvdread/commit/5ec409508803037dfa931591aef93851458d1d2a).

**Comment by jeeb** [comment]
OK, so then I thought maybe if we're only including dvdnav's header, maybe we need to explicitly also include dvdread's dvd_reader.h.

But no, that is actually [still included](https://code.videolan.org/videolan/libdvdnav/blob/dcb9109e45ccd304ec82a7c7bf46cca63620adf9/src/dvdnav/dvdnav.h#L36) in the latest dvdnav.

So this is quite curious.

**Comment by jeeb** [comment]
You could - but you should really check if the header was patched or something since dvdnav's header should include dvdread as well (unconditionally, even). Including dvdnav [5.0.3](https://code.videolan.org/videolan/libdvdnav/blob/5fb919774444aa382f6e02cb63801c82f2c38325/src/dvdnav/dvdnav.h#L36).

So check both versions of dvdnav and dvdread (they technically are separate libraries), and check that both headers are available (`dvdnav/dvdnav.h` is verified, but `dvdread/dvd_reader.h` seems to be there but weird?)

**Comment by Slider-Whistle** [comment]
dvdnav and dvdread seem to both be 5.0.3.

dvdnav/dvdnav.h:
`
...
#include <dvdnav/dvd_types.h>
#include <dvdread/dvd_reader.h>
#include <dvdread/nav_types.h>
#include <dvdread/ifo_types.h> /* For vm_cmd_t */
#include <dvdnav/dvdnav_events.h>
...
`
I've checked, and all of the included files seem to exist.

I installed a decryption library a while ago called libdvdcss, do you know whether that might be interfering at all? The last modified date of dvdread/dvd_reader.h is the same as the other files in the directory, so it doesn't look like it's been patched at all.

**Comment by jeeb** [comment]
Yea, since you were not getting file not found both of the files most probably were there. Check that `dvdread/dvd_reader.h` has the definition of `struct dvd_reader_stream_cb`.

**Comment by Slider-Whistle** [comment]
It doesn't. There's this, though:
/**
 * Opaque type that is used as a handle for one instance of an opened DVD.
 */
typedef struct dvd_reader_s dvd_reader_t;

Guess I should've checked in the first place. Maybe it's some funny things the slackware developers did. Would you recommend that I reinstall it?

**Comment by jeeb** [comment]
[This](https://code.videolan.org/videolan/libdvdread/blob/5.0.3/src/dvdread/dvd_reader.h#L72) is the version of the header that should be in version 5.0.3 of dvdread, and a few lines after that what you've posted the definition should be there.

**Comment by Slider-Whistle** [comment]
Thanks for that.
[228/228] Linking build/mpv
/usr/lib64/gcc/x86_64-slackware-linux/5.5.0/../../../../lib64/libdvdnav.so: undefined reference to `DVDOpenStream'
collect2: error: ld returned 1 exit status

Just editing the header doesn't seem like it's going to work out for me, so I guess I'll just build it myself. I really wonder what's going on with that, though.

**Comment by jeeb** [comment]
Given that our CI system builds with dvdnav/dvdread, it definitely seems like something weird's going on. I'll have to check what lachs0r's docker containers have as a version there.

**Comment by Slider-Whistle** [comment]
I went to get the official slackbuilds just now, and found this thing in PACKAGES.TXT:

PACKAGE NAME:  libdvdnav-6.0.0-x86_64-2.txz
PACKAGE LOCATION:  ./slackware64/l
PACKAGE SIZE (compressed):  52 K
PACKAGE SIZE (uncompressed):  170 K
PACKAGE DESCRIPTION:
libdvdnav: libdvdnav (DVD Navigation Library)
libdvdnav:
libdvdnav: This is mplayer's fork of libdvdnav. libdvdnav is a library that
libdvdnav: allows easy use of sophisticated DVD navigation features such as
libdvdnav: DVD menus, multiangle playback, and even interactive DVD games.
libdvdnav:
libdvdnav: Homepage: https://www.videolan.org/developers/libdvdnav.html
libdvdnav:

I guess that'd be my problem.

**Comment by jeeb** [comment]
Can't really find anything weird in there in those lines. The description is probably outdated although historically accurate. The home page is properly videolan.org, though, and I think the version numbers we're talking about were only released on videolan.org.

**Comment by jeeb** [comment]
Anyways, as far as I can tell this is a system/Slackware issue rather than an mpv issue so will be closing this ticket.

**Comment by Slider-Whistle** [comment]
Alright, thanks for helping out until now.

**Comment by Slider-Whistle** [comment]
Recompiled it using Slackware's build scripts with the official packages, works absolutely fine as far as I can tell. Shame about the actual menu support though, I can always use mplayer for it, but it seems to have worse video output support.
