### PR TITLE
 cocoa-cb: add conditional compilation for Dark Mode features

### LINKED ISSUE #6621: Won't build on macOS 10.13.6: use of unresolved identifier 'NSAppearanceNameDarkAqua'
### mpv version and platform

mpv git HEAD on macOS 10.13.6
```
clang -v
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
```
swift -version
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
```
```
xcode-select -v
xcode-select version 2349.
```

### Expected behavior
Successful build

### Actual behavior
```
/private/tmp/mpv/video/out/cocoa-cb/title_bar.swift:185:44: error: use of unresolved identifier 'NSAppearanceNameDarkAqua'
                return NSAppearance(named: NSAppearanceNameDarkAqua)
                                           ^~~~~~~~~~~~~~~~~~~~~~~~
```
```./bootstrap.py && ./waf configure && ./waf -v``` full output https://0x0.st/zZf4.txt

### PR DESCRIPTION
**Pull request by Akemi**
only the last two commits is relevant. the forward declaration doesn't need to be used, and we could directly use a conditional compilation if wanted.

access to NSVisualEffectView.Material can't be fixed via a forward declaration because the enum can't be extended.

depends on #6635 and #6655, fixes #6621

### CODE REVIEW

**Comment by Akemi** [comment]
i decided agains a cc_check and added a generic check for arbitrary macOS SDK versions.

xcrun can either return the SDK version or the SDK build version. former always only returns the major version, eg "10.14" instead of "10.14.4". which is useless if a minor version change was made, which isn't unusual.

the latter returns a build version which is a combination of 1-2 digits, 1 char and 2-4 digits again (bug fix, not important for us)(example 17A360). the first two numbers are the OS version, eg 17 => 10.13, 18 => 10.14 (offset of 4). the letter corresponds to the minor version, eg A = 0, B = 1, C = 2, etc. some examples of build versions to macOS version:
16E185 => 10.12.4 
17A360 => 10.13
17C76 => 10.13.2
18B71 => 10.14.1
18E219 => 10.14.4

**Comment by jeeb** [comment]
Merged as part of #6703 .
