### ISSUE TITLE
--disable-pthreads is broken for Linux

### ISSUE THREAD

**Issue by Nikoli** [mpv-player/mpv#353]
Building with --disable-pthreads is broken since commit b78d11d3282b118287901bd4f9a220880e27084b

```
osdep/threads.c.10.o: In function `mpthread_cond_timed_wait':
threads.c:(.text+0x29): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
```
