### ISSUE TITLE
Commit 98f5579c024 breaks macosx compilation for OS < 10.12

### ISSUE THREAD

**Issue by maru-sama** [mpv-player/mpv#4783]
Hi,

I am still running with 10.10 on my macbook. Up to commit 98f5579c024 I could compile mpv myself but this commit introduced the following change.

if ([NSWindow respondsToSelector:@selector(allowsAutomaticWindowTabbing)])
            NSWindow.allowsAutomaticWindowTabbing = NO;

allowsAutomaticWindowTabbing has been introduced in 10.12 so it is not available in 10.10. That said respondstoSelector apparenty returns true which then results in 

../osdep/macosx_menubar.m:38:22: error: property 'allowsAutomaticWindowTabbing' not found on object of type 'NSWindow'
            NSWindow.allowsAutomaticWindowTabbing = NO;

I tried figuring out how to check for such a class property but did not succeed so far.

**Comment by Akemi** [comment]
3e2228b2a65b7e4c97ad23d73fdcb32400348e74 should fix it.

**Comment by maru-sama** [comment]
When will this fix make it to current head?

**Comment by Akemi** [comment]
when you tell me that it works for you or alternatively now if you can't/won't test it.

**Comment by maru-sama** [comment]
Understood. I will see if I can do a  quick compile test this evening, since I currently do not have access to the Mac.

**Comment by Argon-** [comment]
Can confirm this fixes compilation on 10.11.

**Comment by maru-sama** [comment]
Sorry for the delayed answer. This change does not fix compilation on 10.10. Apparently the xcode version compatible with 10.10 (7.2.1) does not support this declaration yet.

macosx_compat.h:30:11: error: unknown property attribute 'class'
@property(class) BOOL allowsAutomaticWindowTabbing;

So for the moment I can only think of a compile time guard like

```
+#if (MAC_OS_X_VERSION_MAX_ALLOWED > MAC_OS_X_VERSION_10_10_3)
 
         if ([NSWindow respondsToSelector:@selector(allowsAutomaticWindowTabbing)])
             NSWindow.allowsAutomaticWindowTabbing = NO;

+#endif
```
in macosx_menubar.m itself.

**Comment by Akemi** [comment]
that guard isn't really optimal. on a bundle build with a lower target than 10.12 it will not deactivate that menu item on 10.12. i will look into it again.

**Comment by Akemi** [comment]
599ecfd6831b4306cba838f89e43e1b648c3d5ab should work. instead of the unsupported class property i changed the forward declaration to the setter method.

does this work?

**Comment by Argon-** [comment]
(Works on 10.11)

**Comment by maru-sama** [comment]
Fixes the compilation issue for me on 10.10 as well.

**Comment by maru-sama** [comment]
Just out of curiousity why can I checkout this commit, but do not find it in any commitlog?

**Comment by Akemi** [comment]
k, i will merge it soon.

probably because it's on my [fork](https://github.com/Akemi/mpv/commits/macOS_menubar_fix).

**Comment by maru-sama** [comment]
Argh my mistake. I actually did this before and added it as remote, just forgot that you created a separate branch in your repo for it.
