### ISSUE TITLE
MPV 0.32.0 compilation failed. Execve 'is unavailable: not available on tvos

### ISSUE THREAD

**Issue by asdsjw** [mpv-player/mpv#8016]
### mpv 0.32.0

When I compile MPV in tvos environment, I encounter 'execve' is unavailable: not available on tvos. How to close subprocess-posix.c

[ 68/204] Compiling osdep/subprocess-posix.c
../../../mpv/osdep/subprocess-posix.c:48:16: error: 'execve' is unavailable: not available on tvOS
        return execve(file, argv, envp);
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS13.4.sdk/usr/include/unistd.h:445:6: note: 'execve' has been explicitly marked unavailable here
int      execve(const char * __file, char * const * __argv, char * const * __envp) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
../../../mpv/osdep/subprocess-posix.c:59:13: error: 'execve' is unavailable: not available on tvOS
            execve(fn, argv, envp);
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS13.4.sdk/usr/include/unistd.h:445:6: note: 'execve' has been explicitly marked unavailable here
int      execve(const char * __file, char * const * __argv, char * const * __envp) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
../../../mpv/osdep/subprocess-posix.c:92:12: error: 'fork' is unavailable: not available on tvOS
    fres = fork();
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS13.4.sdk/usr/include/unistd.h:447:8: note: 'fork' has been explicitly marked unavailable here
pid_t    fork(void) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
../../../mpv/osdep/subprocess-posix.c:193:22: error: 'fork' is unavailable: not available on tvOS
        pid_t fres = fork();
                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS13.4.sdk/usr/include/unistd.h:447:8: note: 'fork' has been explicitly marked unavailable here
pid_t    fork(void) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;

**Comment by Akemi** [comment]
the whole build and configure log might be usefull. also pinging @tmm1.

**Comment by tmm1** [comment]
Probably started with 5309497727debfe1b268f915c5a41bdbe93ad9de

I haven't tried to build recent releases for tvOS, but fork/exec are definitely unavailable so this code will need to be wrapped in a configure check/define.

**Comment by wm4** [comment]
Does that mean tvOS has posix_spawn (for what), but not fork/exec?

**Comment by tmm1** [comment]
No posix_spawn either. But I think before wscript would check for that and use it conditionally.

**Comment by asdsjw** [comment]
oks!,I compile with version 0.31.0
I tried to modify files on Xcode, but the player froze on a specific device

**Comment by Akemi** [comment]
the removed check
https://github.com/mpv-player/mpv/commit/9dc0a9f0e0ac448f3aec539531f1078a190b8698
https://github.com/mpv-player/mpv/commit/60f8cd4072ff244618f2c23dd12d6d8b2a5bf5f2#diff-b79856260b3cc9b3e958c83a55bae1e46e31d232125b925c581022786a7bc042

**Comment by tmm1** [comment]
See #9171
