### ISSUE TITLE
Won't build on macOS 10.13.6: use of unresolved identifier 'NSAppearanceNameDarkAqua'

### ISSUE THREAD

**Issue by virus-found** [mpv-player/mpv#6621]
### mpv version and platform

mpv git HEAD on macOS 10.13.6
```
clang -v
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
```
swift -version
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
```
```
xcode-select -v
xcode-select version 2349.
```

### Expected behavior
Successful build

### Actual behavior
```
/private/tmp/mpv/video/out/cocoa-cb/title_bar.swift:185:44: error: use of unresolved identifier 'NSAppearanceNameDarkAqua'
                return NSAppearance(named: NSAppearanceNameDarkAqua)
                                           ^~~~~~~~~~~~~~~~~~~~~~~~
```
```./bootstrap.py && ./waf configure && ./waf -v``` full output https://0x0.st/zZf4.txt
