### PR TITLE
vo_gpu: opengl: use EGL 1.5 API except not really but kind of (???????)

### PR DESCRIPTION
**Pull request by wm4**
This tries to deal with the crazy EGL situation. The summary is that
Mesa was fine with their eglGetDisplay() shithack for years, but may
suddenly feel like not doing it anymore, so we should probably use
eglGetPlatformDisplay(), except that is EGL 1.5 only, and the very
regrettable graphics company (also known as Nvidia) ships drivers (for
old hardware I think) that are EGL 1.4 only, so trying to run mpv there
crashes in the dynamic linker, so we have to go through awful
compatibility because everything is fucking bullshit, Jesus Christ. Did
I mention yet how much I hate EGL? It's supposed to avoid these problems
in the first place, but completely fails at it. What a POS.

I'm not sure whether the EGL 1.5 code path (by parsing the EGL_VERSION)
is really needed, but if you ask me, it feels slightly saner.

Also, unlike before, we actually check the extension string for the
individual platform extensions, because who knows, some EGL
implementations might curse us if we pass unknown platform parameters.
(But actually, the more I think about this, the more bullshit it is.)

X11 and Wayland were the only ones trying to call eglGetPlatformDisplay,
so they're the only ones which are adjusted in this commit.

Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

### CODE REVIEW

**Comment by Dudemanguy** [comment]
Well in case you want me to say it, this works in wayland. Well I have no idea what happens if you try to use a hardware that uses 1.4 + wayland (does wayland even work in 1.4?)

**Comment by mc4man** [comment]
My oldest hardware for nvidia (755m) shouldn't really use the 340 driver but I can throw up a test install and install the 340 driver.
The build continues to fail with these commits, just differently, i.e.


```[197/241] Compiling video/out/vo_x11.c
../video/out/opengl/egl_helpers.c: In function ‘mpegl_get_display’:
../video/out/opengl/egl_helpers.c:325:9: error: unknown type name ‘PFNEGLGETPLATFORMDISPLAYPROC’; did you mean ‘PFNEGLGETPLATFORMDISPLAYEXTPROC’?
         PFNEGLGETPLATFORMDISPLAYPROC GetPlatformDisplay =
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
         PFNEGLGETPLATFORMDISPLAYEXTPROC
../video/out/opengl/egl_helpers.c:326:13: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
             (void *)eglGetProcAddress("eglGetPlatformDisplay");
             ^
../video/out/opengl/egl_helpers.c:329:20: error: called object ‘GetPlatformDisplay’ is not a function or function pointer
             return GetPlatformDisplay(platform, native_display, NULL);
                    ^~~~~~~~~~~~~~~~~~
../video/out/opengl/egl_helpers.c:325:38: note: declared here
         PFNEGLGETPLATFORMDISPLAYPROC GetPlatformDisplay =
                                      ^~~~~~~~~~~~~~~~~~

Waf: Leaving directory `/home/doug/Downloads/mpv-016444c977362210ad3c4d45e6346b17fd90d122/build'
Build failed

**Comment by mc4man** [comment]
If you use PFNEGLGETPLATFORMDISPLAYEXTPROC then the build succeeds & the resultant mpv will run but only with gpu-context=x11, otherwise segfaults.

Maybe users of such old hardware should feel fortunate to be able to use 0.30 as is & if wishing to move on with mpv then move on with their hardware..
(- nvidia driver  390.xx is min to work without any changes to current master, atm  396.24 to use nvdec & be free of the whole mess.

**Comment by wm4** [comment]
You need to build with EGL 1.5 headers, or are you saying that there are EGL 1.5 headers without PFNEGLGETPLATFORMDISPLAYPROC?

For our uses, the definitions should be compatible, though.

>If you use PFNEGLGETPLATFORMDISPLAYEXTPROC then the build succeeds & the resultant mpv will run but only with gpu-context=x11, otherwise segfaults.

Point out where it segfaults, and post eglinfo output.

**Comment by wm4** [comment]
No response? I'll probably just merge this, since there's a slight chance it guarantees more correctness than without.

**Comment by wm4** [comment]
Merged manually, with some changes.
