### ISSUE TITLE
mpv-0.3.11 fails to build with libav-9.13

### ISSUE THREAD

**Issue by Nikoli** [mpv-player/mpv#876]
Please fix build or deps in waf.

```
[ 66/232] c: demux/demux.c -> build/demux/demux.c.10.o
19:42:15 runner ['x86_64-pc-linux-gnu-gcc', '-march=core2', '-O2', '-pipe', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wno-switch', '-Wno-parentheses', '-Wpointer-arith', '-Wredundant-decls', '-Wno-pointer-sign', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-DNO_BUILD_TIMESTAMPS', '-pthread', '-I/var/package-manager/tmp/portage/media-video/mpv-0.3.11/work/mpv-0.3.11/build', '-I/var/package-manager/tmp/portage/media-video/mpv-0.3.11/work/mpv-0.3.11', '-I/usr/include/alsa', '-I/usr/include/harfbuzz', '-I/usr/include/fribidi', '-I/usr/include/glib-2.0', '-I/usr/lib64/glib-2.0/include', '-I/usr/include/freetype2', '../demux/demux.c', '-c', '-o', 'demux/demux.c.10.o']
../demux/demux.c: In function 'packet_destroy':
../demux/demux.c:116:5: error: implicit declaration of function 'av_free' [-Werror=implicit-function-declaration]
../demux/demux.c: In function 'new_demux_packet':
../demux/demux.c:142:5: error: implicit declaration of function 'av_malloc' [-Werror=implicit-function-declaration]
../demux/demux.c:142:16: warning: assignment makes pointer from integer without a cast [enabled by default]
../demux/demux.c: In function 'demux_open':
../demux/demux.c:596:21: warning: value computed is not used [-Wunused-value]
../demux/demux.c: At top level:
../demux/demux.c:179:13: warning: 'destroy_avpacket' defined but not used [-Wunused-function]
cc1: some warnings being treated as errors
Waf: Leaving directory `/var/package-manager/tmp/portage/media-video/mpv-0.3.11/work/mpv-0.3.11/build'
Build failed
 -> task in 'mpv' failed (exit status 1): 
        {task 383078565136: c demux.c -> demux.c.10.o}
['x86_64-pc-linux-gnu-gcc', '-march=core2', '-O2', '-pipe', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wno-switch', '-Wno-parentheses', '-Wpointer-arith', '-Wredundant-decls', '-Wno-pointer-sign', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-DNO_BUILD_TIMESTAMPS', '-pthread', '-I/var/package-manager/tmp/portage/media-video/mpv-0.3.11/work/mpv-0.3.11/build', '-I/var/package-manager/tmp/portage/media-video/mpv-0.3.11/work/mpv-0.3.11', '-I/usr/include/alsa', '-I/usr/include/harfbuzz', '-I/usr/include/fribidi', '-I/usr/include/glib-2.0', '-I/usr/lib64/glib-2.0/include', '-I/usr/include/freetype2', '../demux/demux.c', '-c', '-o', 'demux/demux.c.10.o']
```
