### ISSUE TITLE
Doesn't build with ffmpeg 4.4

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#13454]
```
FAILED: libmpv.so.2.2.0.p/video_out_hwdec_hwdec_drmprime.c.o 
cc -Ilibmpv.so.2.2.0.p -I. -I.. -Isubprojects/libplacebo/src/include -I../subprojects/libplacebo/src/include -Icommon -Ietc -Iplayer/javascript -Iplayer/lua -Isub -Ivideo/out -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/lua5.2 -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/libdrm -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -std=c11 -O2 -g -D_FILE_OFFSET_BITS=64 -Werror=implicit-function-declaration -Wempty-body -Wdisabled-optimization -Wstrict-prototypes -Wno-format-zero-length -Wno-redundant-decls -Wvla -Wno-format-truncation -Wimplicit-fallthrough -fno-math-errno -Wformat -Werror=format-security -Wundef -Wmissing-prototypes -Wshadow -Wno-switch -Wparentheses -Wpointer-arith -Wno-pointer-sign -Wno-unused-result -D_GNU_SOURCE -fPIC -D_REENTRANT -pthread -MD -MQ libmpv.so.2.2.0.p/video_out_hwdec_hwdec_drmprime.c.o -MF libmpv.so.2.2.0.p/video_out_hwdec_hwdec_drmprime.c.o.d -o libmpv.so.2.2.0.p/video_out_hwdec_hwdec_drmprime.c.o -c ../video/out/hwdec/hwdec_drmprime.c
In file included from ../mpv_talloc.h:7,
                 from ../misc/bstr.h:27,
                 from ../video/img_format.h:25,
                 from ../video/out/vo.h:29,
                 from ../video/out/drm_common.h:24,
                 from ../video/out/hwdec/hwdec_drmprime.c:34:
../video/out/hwdec/hwdec_drmprime.c: In function 'init':
../video/out/hwdec/hwdec_drmprime.c:136:64: error: 'AV_PIX_FMT_P210' undeclared (first use in this function); did you mean 'AV_PIX_FMT_Y210'?
  136 |     MP_TARRAY_APPEND(p, p->formats, num_formats, pixfmt2imgfmt(AV_PIX_FMT_P210));
      |                                                                ^~~~~~~~~~~~~~~
../ta/ta_talloc.h:106:26: note: in definition of macro 'MP_TARRAY_APPEND'
  106 |         (p)[(idxvar)] = (__VA_ARGS__);              \
      |                          ^~~~~~~~~~~
../video/out/hwdec/hwdec_drmprime.c:136:64: note: each undeclared identifier is reported only once for each function it appears in
  136 |     MP_TARRAY_APPEND(p, p->formats, num_formats, pixfmt2imgfmt(AV_PIX_FMT_P210));
      |                                                                ^~~~~~~~~~~~~~~
../ta/ta_talloc.h:106:26: note: in definition of macro 'MP_TARRAY_APPEND'
  106 |         (p)[(idxvar)] = (__VA_ARGS__);              \
      |                          ^~~~~~~~~~~
```

regressed by d90a5ff17a88cbda2ac64cccf1cd98456f2d0ab2
ping @philipl

**Comment by philipl** [comment]
Ok. I'll conditionalise it.
