### ISSUE TITLE
mpv fails to build with clang on OS X due to 9871463

### ISSUE THREAD

**Issue by zmwangx** [mpv-player/mpv#1199]
Due to [player/lua.c line 1259](https://github.com/mpv-player/mpv/blame/master/player/lua.c#L1259) introduced in 9871463, mpv now won't build with clang-600.0.51 on OS X 10.9.5. The function `kill` wasn't declared (`signal.h` not included, I suppose?) according to the error messages:

```
../player/lua.c:1259:9: error: implicit declaration of function 'kill' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        kill(pid, SIGKILL);
        ^
1 error generated.

Waf: Leaving directory `/Users/zmwang/software/mpv/build'
Build failed
 -> task in 'mpv' failed (exit status 1):
    {task 4474871568: c lua.c -> lua.c.12.o}
['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Wno-logical-op-parentheses', '-fcolor-diagnostics', '-Wno-tautological-compare', '-Wno-tautological-constant-out-of-range-compare', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wno-parentheses', '-Wpointer-arith', '-Wredundant-decls', '-Wno-pointer-sign', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wempty-body', '-Wdisabled-optimization', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-pthread', '-I/Users/zmwang/software/mpv/build', '-I/Users/zmwang/software/mpv', '-I/opt/local/include', '-I/opt/local/include/quvi-0.9', '-I/opt/local/include/freetype2', '-I/opt/local/include/fribidi', '-I/opt/local/include/glib-2.0', '-I/opt/local/lib/glib-2.0/include', '-DHAVE_LIBAVRESAMPLE=1', '-DHAVE_DVDNAV=1', '-DHAVE_DVDREAD=1', '-DHAVE_LCMS2=1', '-DHAVE_LIBAV=1', '-DHAVE_LIBAVFILTER=1', '-DHAVE_MPG123=1', '-DHAVE_LIBQUVI9=1', '-DHAVE_LIBPOSTPROC=1', '-DHAVE_LIBBLURAY=1', '-DHAVE_XRANDR=1', '-DHAVE_LIBAVDEVICE=1', '-DHAVE_XEXT=1', '-DHAVE_52=1', '-DHAVE_X11=1', '-DHAVE_LIBASS=1', '../player/lua.c', '-c', '-o', '/Users/zmwang/software/mpv/build/player/lua.c.12.o']
```
