### ISSUE TITLE
master fails to build with ffmpeg 4.1.4

### ISSUE THREAD

**Issue by arekm** [mpv-player/mpv#7471]
### mpv version and platform versions

git master 36ca0e00305fdc3d5c052c4757b00a33b2eb6b14

### Reproduction steps

commit 7d11eda72e90d7aa9df25127bd810aa7b191029c
dropped ifdefs around AV_PIX_FMT_NV24 which causes build failures with ffmpeg 4.1.4

To reproduce try building current git master (36ca0e00305fdc3d5c052c4757b00a33b2eb6b14) with ffmpeg 4.1.4

### Expected behavior

build fine

### Actual behavior
````
13:18:36 runner ['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_FILE_OFFSET_BITS=64', '-Wall', '-std=c11', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wno-format-truncation', '-Wimplicit-fallthrough', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-pthread', '-I.', '-I..', '-I/usr/include/libdrm', '-I/usr/include/x86_64-linux-gnu', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/uuid', '-I/usr/include/fribidi', '-I/usr/include/freetype2', '-I/usr/include/libpng16', '../common/version.c', '-c', '-o/home/arekm/test/mpv/build/common/version.c.20.o']
../video/fmt-conversion.c:39:20: error: ‘AV_PIX_FMT_NV24’ undeclared here (not in a function); did you mean ‘AV_PIX_FMT_NV21’?
   39 |     {IMGFMT_NV24,  AV_PIX_FMT_NV24},
      |                    ^~~~~~~~~~~~~~~
      |                    AV_PIX_FMT_NV21

Waf: Leaving directory `/home/arekm/test/mpv/build'
````
